apiVersion: v1
kind: Service
metadata:
  name: vetri-flask-service
spec:
  selector:
    app: vetri-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
